### ISSUE TITLE
the image in laravel page is wrong

### ISSUE THREAD

**Issue by ghost** [Open-Source-Community/oscgeeks.org#2]
it's supposed to be just the laravel logo. I don't know where did the current image come from.

**Comment by zeyadetman** [comment]
You mean this ?
![ScreenShot](https://preview.ibb.co/dXdnD6/sasd.jpg)

**Comment by Mostafa-Ahmed** [comment]
مش فاهم؟!

**Comment by ghost** [comment]
yes I mean this :D
It's supposed to be the laravel logo.

**Comment by zeyadetman** [comment]
@lordadamson  Ok. I'll fix it so soon. Thanks

**Comment by ghost** [comment]
You welcome sir :D
