### ISSUE TITLE
Close the debugging mode. The website is in production now :D

### ISSUE THREAD

**Issue by ghost** [Open-Source-Community/oscgeeks.org#4]
You can close it from the .env file. Set the debug variable to false.

**Comment by zeyadetman** [comment]
check again. @lordadamson

**Comment by ghost** [comment]
![screenshot from 2017-10-24 20-43-00](https://user-images.githubusercontent.com/6195060/31961755-f4d5d54e-b8fb-11e7-9ede-aaa27253df1d.png)
sounds like we're still in debug mode.

**Comment by ghost** [comment]
any reason for the wontfix label? :D

**Comment by zeyadetman** [comment]
@lordadamson We working on it. thanks.

**Comment by ghost** [comment]
cool :D

**Comment by AmrAbdelhameed** [comment]
Done :D
