### ISSUE TITLE
your domain is routing to my website

### ISSUE THREAD

**Issue by Zethson** [Open-Source-Community/oscgeeks.org#6]
https://oscgeeks.org/index

What is going on with your domain?!?

**Comment by lordadamson** [comment]
Hey thanks for the heads up man :smile: 
I'm not active in this community anymore but I notified them and they seem to have worked on it because it now points to some nginx hello world :smile:

**Comment by Zethson** [comment]
No it doesn't.
See: https://oscgeeks.org/index

**Comment by lordadamson** [comment]
oh wait the https still points to your website... damn it

**Comment by lordadamson** [comment]
@Satharus will someone please look into this?

**Comment by Satharus** [comment]
We are looking into it. It seems that there's an issue with HTTPS. 
@anieo , can you please check this with the head of the web committee @eslam-mamdouh ? 

@Zethson We are sorry for the late reply.

**Comment by Zethson** [comment]
It weren't an issue for me if google wouldn't select your URL as the canonical :)

**Comment by Satharus** [comment]
@Zethson 

We are going to fix this issue ASAP. 

We are a student community and we are currently in the middle of our final exams, so that's why it's taking some time :( . 

I am very sorry for this inconvenience.

**Comment by Zethson** [comment]
Thank you very much!
I share your destiny - a student approaching my exams in the coming weeks :)

**Comment by Satharus** [comment]
No need at all! :)

Best of luck to you in your exams. I hope you do amazing :smiley: 

I'll keep you updated once we fix this.

**Comment by Satharus** [comment]
Hello @Zethson 

First of all, I am deeply sorry for the late action. 

Anyhow, we have finally resolved the issue for now until we get our website up and running :smiley:!

https://oscgeeks.org/ Give it a try and tell us if you have any issues.

Also on a personal note, I noticed when you opened this issue that you're Zeth from StarCraft 2 which is amazing tbh hahahaha. I absolutely love the game and I play it a lot with my college friends, some of which are in this community.

Thank you so much for your patience and we're all sorry for any inconveniences caused. 

Good luck to you!

**Comment by Zethson** [comment]
Dear @Satharus,

thank you very much for resolving this matter!
Out of curiosity, what was the actual issue? How did your domain/server even select my site?

Yup, that's me :) 
Amazing to see fellow Starcraft fans! I've been inactive for quite some years now, but really miss the game.

Thank you again!
Cheers

**Comment by Satharus** [comment]
The issue was that our server had expired and we weren't going to renew it until our new website is finished so that we can do it all in one batch.

Our domain (oscgeeks.org) was still pointing to the IP of our (ex)Digital Ocean droplet which just happened to be the IP of your website when our droplet was deleted since we didn't renew it haha.

So yeah we just have it setup on some free hosting site for now until we configure our new website. 

If you ever get back into StarCraft hit me up! I am sure I can learn A LOT from you :smile:. I'm Satharus#2202 on Battle.net.

Thanks a lot!

**Comment by Zethson** [comment]
Ahh, I see.
I was really trying hard to figure out what was wrong with my setup haha.

Will do!

**Comment by Satharus** [comment]
Glad we were able to fix it. 

Cheers, man. Have a good one!
